### PR TITLE
Upgrade paper.js to 0.10.2

### PR DESCRIPTION
**Pull request by madbook**
> This fixes snoovatars in Chrome

For https://reddit.atlassian.net/browse/CE-449
Relevant github issue https://github.com/paperjs/paper.js/issues/1222

Something updated in Chrome recently that broke paper.js, the SVG library we use in snoovatars.  This bumps the library to the latest version, which fixes the issue.

This is a pretty huge diff – I've done a quick skim and it seems fine.

👓 @andytuba

### CODE REVIEW

**Comment by andytuba** [comment]
Should we use the dist/minified version instead of develop? `paper.js-0.10.2/dist/paper-core.min.js` or `paper.js-0.10.2/dist/paper-core.js` in the [v0.10.2 release download](https://github.com/paperjs/paper.js/releases/tag/v0.10.2).

**Comment by andytuba** [comment]
Fixes https://github.com/reddit/reddit/issues/1746

**Comment by madbook** [comment]
Ah, thanks for the compare link to their repo, good thinking!  It's not necessary to use the min version they provide – it all gets minified by our build process anyways (and actually I'm not sure if double-minifying is a good idea).  Generally we use unminified 3rd party libs.

**Comment by andytuba** [comment]
:fish:

**Pull request merged**
